apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: app
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: ko://github.com/izaakdale/hello-server
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: app
spec:
  selector:
    app: hello
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hello
  namespace: app
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`api.izaakserver.com`) && PathPrefix(`/hello`)
      services:
        - kind: Service
          name: hello
          namespace: app
          port: 80
      middlewares:
        - name: stripprefix
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
  namespace: app
spec:
  stripPrefix:
    prefixes:
      - /hello
---